{
 "title": "user",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vehicletemp",
     "rawSql": "SELECT\r\n  driver_id AS \"운전자 ID\"\r\nFROM vehicle_data\r\nWHERE vehicle_id = 'car_1'\r\n  AND driver_id IS NOT NULL\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 6, "y": 0 },
   "targets": [
    { "dataset": "vehicletemp" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vehicletemp",
     "rawSql": "SELECT\r\n  to_timestamp(\"timestamp\") AS last_time\r\nFROM vehicle_data\r\nWHERE vehicle_id = 'car_1'\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "engine",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vehicletemp",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN engine_on THEN 'ON'\r\n    ELSE 'OFF'\r\n  END AS \"엔진 상태\"\r\nFROM vehicle_data\r\nWHERE vehicle_id = 'car_1'\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 10, "x": 6, "y": 3 },
   "targets": [
    {
     "dataset": "vehicletemp",
     "rawSql": "SELECT\r\n  \"timestamp\" AS time,\r\n  vehicle_id,\r\n  lat,\r\n  lon\r\nFROM vehicle_data\r\nWHERE vehicle_id = 'car_1'\r\n  AND lat IS NOT NULL\r\n  AND lon IS NOT NULL\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "options": {
    "content": "<h1 style=\"text-align:center; color:#10ebe0; font-size:36px; font-family:georgia,serif;\">Tuscon</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 6 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n  <img\n    src=\"https://8team-dashboard-images.s3.ap-northeast-2.amazonaws.com/picture/tucson.png\"\n    alt=\"tucson\"\n    style=\"max-width:100%; height:auto; border-radius:12px;\"\n  />\n</div>"
   }
  },
  {
   "title": "mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vehicletemp",
     "rawSql": "SELECT\r\n  CASE mode\r\n    WHEN 1 THEN '주행'\r\n    WHEN 2 THEN '정차'\r\n    WHEN 3 THEN '시동 꺼짐'\r\n    ELSE '알 수 없음'\r\n  END AS \"주행 상태\"\r\nFROM vehicle_data\r\nWHERE vehicle_id = 'car_1'\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Current Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vehicletemp",
     "rawSql": "SELECT\r\n  speed AS \"현재 속도\"\r\nFROM vehicle_data\r\nWHERE vehicle_id = 'car_1'\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \n  fuel\nFROM vehicle_data\nWHERE vehicle_id = 'car_1'\n  AND fuel IS NOT NULL\nORDER BY \"timestamp\" DESC\nLIMIT 1;"
    }
   ]
  }
 ]
}