- name: Consumer 작업용 루트(앱) 디렉토리 생성
  file:
    path: "/home/{{ ansible_user }}/consumer-app/app"
    state: directory
    mode: '0755'

- name: Python 정제기 코드 및 의존성 파일 복사
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/consumer-app/app/{{ item }}"
  loop:
    - processor.py
    - requirements.txt

- name: "Docker Compose 파일 배포"
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/consumer-app/docker-compose.yml"

- name: "최신 이미지 풀(Pull) 받기"
  shell:
    # 빌드 서버(GitHub Actions)가 올려둔 이미지를 내려받음
    cmd: "docker compose pull"
    chdir: "/home/{{ ansible_user }}/consumer-app"
  become: yes

- name: "컨테이너 실행"
  shell:
    # 이미지가 이미 있으므로 빌드 없이 바로 실행
    cmd: "docker compose up -d"
    chdir: "/home/{{ ansible_user }}/consumer-app"
  become: yes

- name: Kafka Connect 서비스 안정화 대기
  pause:
    seconds: 30
    prompt: "Consumer 앱과 Connector가 완전히 뜰 때까지 기다립니다."

- name: "Azure Blob Storage Sink 커넥터 설정 (Raw Data)"
  uri:
    url: "http://localhost:8083/connectors"
    method: POST
    body_format: json
    body:
      name: "azure-blob-raw-sink"
      config:
        connector.class: "io.aiven.kafka.connect.azure.sink.AzureBlobSinkConnector"
        tasks.max: "1"
        topics: "raw_topic"
        key.converter: "org.apache.kafka.connect.storage.StringConverter"
        value.converter: "org.apache.kafka.connect.json.JsonConverter"
        value.converter.schemas.enable: "false"
        azure.storage.connection.string: "DefaultEndpointsProtocol=https;AccountName={{ azure_storage_account_name }};AccountKey={{ azure_storage_primary_key }};EndpointSuffix=core.windows.net"
        azure.storage.container.name: "raw-topic-container"
        format.output.fields: "value"
        format.output.type: "json"
        flush.size: "100"
    status_code: [201, 409]
  register: connect_result
  until: "connect_result.status is defined and (connect_result.status == 201 or connect_result.status == 409)"
  retries: 20
  delay: 15

- name: "AWS S3 Sink 커넥터 설정 (Cleansed Data)"
  uri:
    url: "http://localhost:8083/connectors"
    method: POST
    body_format: json
    body:
      name: "aws-s3-cleansed-sink"
      config:
        connector.class: "io.confluent.connect.s3.S3SinkConnector"
        tasks.max: "1"
        topics: "cleansed_topic"
        key.converter: "org.apache.kafka.connect.storage.StringConverter"
        value.converter: "org.apache.kafka.connect.json.JsonConverter"
        value.converter.schemas.enable: "false"
        s3.bucket.name: "{{ s3_bucket_name }}"
        s3.region: "ap-northeast-2"
        aws.access.key.id: "{{ aws_access_key }}"
        aws.secret.access.key: "{{ aws_secret_key }}"
        format.class: "io.confluent.connect.s3.format.json.JsonFormat" # 분석용 JSONL
        line.separator: "\n"
        storage.class: "io.confluent.connect.s3.storage.S3Storage"
        flush.size: "100"
    status_code: [201, 409]