services:
  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.6.1
    container_name: kafka-connect
    restart: unless-stopped
    ports:
      - "${KAFKA_CONNECT_PORT:-8083}:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${BROKER_BOOTSTRAP_SERVERS}
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: azure-consumer-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
    volumes:
      - ./plugins:/etc/kafka-connect/jars
    networks:
      - consumer-net

  processor:
    build:
      context: ./processor
    container_name: kafka-processor
    restart: unless-stopped
    environment:
      BROKER_BOOTSTRAP_SERVERS: ${BROKER_BOOTSTRAP_SERVERS}
      RAW_TOPIC: ${RAW_TOPIC}
      CLEANSED_TOPIC: ${CLEANSED_TOPIC}
      CONSUMER_GROUP_ID: ${PROCESSOR_CONSUMER_GROUP_ID}
    depends_on:
      - kafka-connect
    networks:
      - consumer-net

networks:
  consumer-net:
    driver: bridge
